
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	
	private global::Gtk.Button CreateBtn;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.CreateBtn = new global::Gtk.Button ();
		this.CreateBtn.CanFocus = true;
		this.CreateBtn.Name = "CreateBtn";
		this.CreateBtn.UseUnderline = true;
		this.CreateBtn.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.fixed1.Add (this.CreateBtn);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.CreateBtn]));
		w1.X = 13;
		w1.Y = 106;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.CreateBtn.Clicked += new global::System.EventHandler (this.CreateBtnClick);
	}
}
