
// This file has been generated by the GUI designer. Do not modify.
namespace Pony.GtkSharp.Demo
{
	public partial class ItemEditor
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Pony.GtkSharp.Demo.ItemEditor
			this.Name = "Pony.GtkSharp.Demo.ItemEditor";
			this.Title = global::Mono.Unix.Catalog.GetString ("ItemEditor");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
