
// This file has been generated by the GUI designer. Do not modify.
namespace Pony.GtkSharp.Demo
{
	public partial class ItemEd
	{
		private global::Gtk.Fixed fixed1;
		
		private global::Gtk.Entry NameEditor;
		
		private global::Gtk.Entry entry2;
		
		private global::Gtk.Entry entry3;
		
		private global::Gtk.Button OkBtn;
		
		private global::Gtk.Button CancelBtn;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Pony.GtkSharp.Demo.ItemEd
			this.Name = "Pony.GtkSharp.Demo.ItemEd";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child Pony.GtkSharp.Demo.ItemEd.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.NameEditor = new global::Gtk.Entry ();
			this.NameEditor.CanFocus = true;
			this.NameEditor.Name = "NameEditor";
			this.NameEditor.IsEditable = true;
			this.NameEditor.InvisibleChar = '●';
			this.fixed1.Add (this.NameEditor);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.NameEditor]));
			w2.X = 2;
			w2.Y = 5;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entry2 = new global::Gtk.Entry ();
			this.entry2.CanFocus = true;
			this.entry2.Name = "entry2";
			this.entry2.IsEditable = true;
			this.entry2.InvisibleChar = '●';
			this.fixed1.Add (this.entry2);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entry2]));
			w3.X = 2;
			w3.Y = 35;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entry3 = new global::Gtk.Entry ();
			this.entry3.CanFocus = true;
			this.entry3.Name = "entry3";
			this.entry3.IsEditable = true;
			this.entry3.InvisibleChar = '●';
			this.fixed1.Add (this.entry3);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entry3]));
			w4.X = 2;
			w4.Y = 65;
			w1.Add (this.fixed1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(w1 [this.fixed1]));
			w5.Position = 0;
			// Internal child Pony.GtkSharp.Demo.ItemEd.ActionArea
			global::Gtk.HButtonBox w6 = this.ActionArea;
			w6.Name = "dialog1_ActionArea";
			w6.Spacing = 10;
			w6.BorderWidth = ((uint)(5));
			w6.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.OkBtn = new global::Gtk.Button ();
			this.OkBtn.CanFocus = true;
			this.OkBtn.Name = "OkBtn";
			this.OkBtn.UseStock = true;
			this.OkBtn.UseUnderline = true;
			this.OkBtn.Label = "gtk-ok";
			this.AddActionWidget (this.OkBtn, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w6 [this.OkBtn]));
			w7.Expand = false;
			w7.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.CancelBtn = new global::Gtk.Button ();
			this.CancelBtn.CanFocus = true;
			this.CancelBtn.Name = "CancelBtn";
			this.CancelBtn.UseStock = true;
			this.CancelBtn.UseUnderline = true;
			this.CancelBtn.Label = "gtk-cancel";
			this.AddActionWidget (this.CancelBtn, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w8 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w6 [this.CancelBtn]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
